### ISSUE TITLE
Incompatible with IntelliJ IDEA 2024.2

### ISSUE THREAD

**Issue by sirmacik** [brig/concord-intellij-ng#16]
Hi!
Unfortunately recent release of IDEA reports incompatibility with concord plugin. 

> Not compatible with the version of your running IDE (IntelliJ IDEA 2024.2)
> Compatible with IntelliJ IDEA (Ultimate, Community), Android Studio, AppCode, Aqua, CLion, Code With Me Guest, DataGrip, DataSpell, GoLand, JetBrains Client, MPS, PhpStorm, PyCharm (Professional, Community), Rider, RubyMine, RustRover, WebStorm, Writerside

**Comment by brig** [comment]
The new version, compatible with IntelliJ IDEA 2024.2, will be available in a few days. It is now pending JetBrains' review and approval.

**Comment by sirmacik** [comment]
PR closed as advised. Thank you very much for such a quick fix. I see that lots of changes were needed unfortunately.

**Comment by sirmacik** [comment]
Built it locally and it works really well. Thank you. Looking forward to jetbrains review.

**Comment by brig** [comment]
Is there anything missing in the plugin? What additional functionality would be useful? Any ideas are welcome:)

**Comment by brig** [comment]
Version 0.7.0 (with IDEA 2024.2 support) of the Concord plugin has been approved by JetBrains and is now publicly available

**Comment by sirmacik** [comment]
Amazing, thanks! Closing the ticket. Will reach out with any improvement ideas when they occur (:
